version: '3'

services:
  db-blog-cf:
    container_name: db-wordpress-blog
    image: mariadb:10.4
    volumes:
      - ../data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_comf_db
      - MYSQL_USER=blog_comf_user
      - MYSQL_PASSWORD=root
    ports:
      - '3323:3306'
    networks:
      - blog_comf_network
  web-blog-cf:
    container_name: web-wordpress-blog
    image: wordpress:6.4
    depends_on:
      - db-blog-cf
    volumes:
      - ../wordpress-full:/var/www/html
      - ./:/var/www/html/wp-content/themes/blog-comf
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_HOST=db-wordpress-blog
      - WORDPRESS_DB_NAME=blog_comf_db
      - WORDPRESS_DEBUG=true
    ports:
      - 8102:80
    networks:
      - blog_comf_network
networks:
  blog_comf_network:
    driver: bridge